final List<Map<String, dynamic>> plantList = [
  {
    'name': 'Aloe Vera',
    'imageUrl':
        'https://www.shutterstock.com/image-photo/aloe-vera-plant-sleek-white-600nw-2504122305.jpg',
    'soilType': 'Sandy',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Indoor'],
    'description': 'A medicinal plant with gel-filled leaves.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Spider Plant',
    'imageUrl':
        'https://www.plantvine.com/plants/Variegated-Spider-Plant-2-800x1000.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Moderate', 'Humid'],
    'categoryType': ['Indoor'],
    'description': 'A fast-growing plant with striped leaves.',
    'minTemp': 18.0,
    'maxTemp': 32.0,
  },
  {
    'name': 'Rose',
    'imageUrl':
        'https://bouqs.com/blog/wp-content/uploads/2018/08/shutterstock_1662182848-min-1080x719.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Garden', 'Outdoor'],
    'description': 'A fragrant flower known for its beauty.',
    'minTemp': 20.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Tulip',
    'imageUrl':
        'https://gardenerspath.com/wp-content/uploads/2023/05/Large-Mass-Planting-of-Tulips-Featured.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Cool', 'Sunny'],
    'categoryType': ['Garden', 'Outdoor'],
    'description': 'A bulbous plant with colorful flowers.',
    'minTemp': 10.0,
    'maxTemp': 25.0,
  },
  {
    'name': 'Cactus',
    'imageUrl': 'https://bindy.com.au/wp-content/uploads/2024/05/cactus-2.jpg',
    'soilType': 'Sandy',
    'weatherType': ['Dry', 'Hot'],
    'categoryType': ['Outdoor'],
    'description': 'A succulent plant known for its thick, spiny stems.',
    'minTemp': 20.0,
    'maxTemp': 40.0,
  },
  {
    'name': 'Lavender',
    'imageUrl':
        'https://5.imimg.com/data5/SELLER/Default/2024/6/427051984/JG/CH/PQ/46470149/51hmo-cuul-ac-uf1000-1000-ql80.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Sunny', 'Dry'],
    'categoryType': ['Garden', 'Outdoor'],
    'description': 'A fragrant purple flower known for its calming scent.',
    'minTemp': 10.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Basil',
    'imageUrl':
        'https://cdn.pixabay.com/photo/2018/07/12/02/32/basil-3532424_640.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Indoor'],
    'description': 'A fragrant herb used in cooking.',
    'minTemp': 15.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Sunflower',
    'imageUrl':
        'https://images.squarespace-cdn.com/content/v1/582b872529687fd6acb7423d/1576164674617-6KKTQ82NN1W7RX1NDAZU/IMG_0848-2.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Sunny', 'Hot'],
    'categoryType': ['Outdoor', 'Garden'],
    'description': 'A large, bright yellow flower that follows the sun.',
    'minTemp': 15.0,
    'maxTemp': 40.0,
  },
  {
    'name': 'Fern',
    'imageUrl':
        'https://cdn11.bigcommerce.com/s-1b9100svju/product_images/uploaded_images/all-about-ferns6.jpg',
    'soilType': 'Moist, Well-drained',
    'weatherType': ['Tropical', 'Humid'],
    'categoryType': ['Indoor', 'Outdoor'],
    'description': 'A leafy, non-flowering plant found in moist environments.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Begonia',
    'imageUrl':
        'https://cdn.britannica.com/42/198142-050-48DAB6F3/Wax-Begonia-cucullata-flower.jpg',
    'soilType': 'Well-drained, Rich',
    'weatherType': ['Moderate', 'Humid'],
    'categoryType': ['Indoor'],
    'description': 'A flowering plant with attractive, colored foliage.',
    'minTemp': 18.0,
    'maxTemp': 28.0,
  },
  {
    'name': 'Mint',
    'imageUrl':
        'https://plantura.garden/uk/wp-content/uploads/sites/2/2022/06/mint.jpg',
    'soilType': 'Moist, Well-drained',
    'weatherType': ['Moderate', 'Sunny'],
    'categoryType': ['Indoor', 'Outdoor'],
    'description': 'A fragrant herb often used in beverages and cooking.',
    'minTemp': 12.0,
    'maxTemp': 25.0,
  },
  {
    'name': 'Orchid',
    'imageUrl':
        'https://images.immediate.co.uk/production/volatile/sites/10/2018/02/71414dae-3e69-48a1-bfb1-42681acbeedd-5e5b449.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Tropical', 'Warm'],
    'categoryType': ['Indoor'],
    'description': 'A beautiful flowering plant known for its diversity.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Lily',
    'imageUrl':
        'https://static.themarthablog.com/2020/07/MVIMG_20200724_090616-scaled.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Cool', 'Sunny'],
    'categoryType': ['Garden'],
    'description': 'A fragrant flower that blooms in a variety of colors.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Jade Plant',
    'imageUrl':
        'https://www.gardnermuseum.org/sites/default/files/styles/portrait_large/public/2023-11/Landscape_Courtyard_Holiday_07.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Sunny', 'Dry'],
    'categoryType': ['Indoor'],
    'description': 'A succulent plant known for its rounded, fleshy leaves.',
    'minTemp': 10.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Pothos',
    'imageUrl':
        'https://www.familyhandyman.com/wp-content/uploads/2022/08/GettyImages-1399892210-pothos-plant-e1661524380829.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Moderate', 'Humid'],
    'categoryType': ['Indoor'],
    'description': 'A low-maintenance vine with heart-shaped leaves.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Zinnia',
    'imageUrl':
        'https://t3.ftcdn.net/jpg/02/04/77/86/360_F_204778668_0PQQuQWZhAxdqnOynz41e7NLBFOsUQKL.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Sunny', 'Hot'],
    'categoryType': ['Garden'],
    'description': 'A colorful flower known for its bright blooms.',
    'minTemp': 15.0,
    'maxTemp': 40.0,
  },
  {
    'name': 'Bamboo',
    'imageUrl':
        'https://environmentcontrols.co.uk/wp-content/uploads/sites/3/2022/10/Bamboo-7.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Moderate', 'Tropical'],
    'categoryType': ['Outdoor'],
    'description': 'A tall grass known for its fast growth and versatility.',
    'minTemp': 15.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Chrysanthemum',
    'imageUrl':
        'https://d9zqppyx20g7i.cloudfront.net/blog/34739/how_to_get_your_chrysanthemum_blooms_to_last_longer__large.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Cool', 'Sunny'],
    'categoryType': ['Garden'],
    'description': 'A colorful flower often associated with fall.',
    'minTemp': 10.0,
    'maxTemp': 25.0,
  },
  {
    'name': 'Ficus',
    'imageUrl':
        'https://diacos.com.au/app/uploads/2022/08/plant-ficus-benjamina-in-a-dark-brown-pot-2021-09-03-06-38-22-utc-scaled-e1661744766283-1003x1200.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Moderate', 'Sunny'],
    'categoryType': ['Indoor'],
    'description':
        'A tree that produces figs and is popular as an ornamental plant.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Geranium',
    'imageUrl':
        'https://www.marthastewart.com/thmb/BiG7k7D220LDIjhpWm_6QLNjW-k=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/geraniums-getty-0623-f13d2a604ef84a6981cd45acaead535f.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Garden'],
    'description': 'A flowering plant known for its vibrant colors.',
    'minTemp': 15.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Tomato',
    'imageUrl':
        'https://t3.ftcdn.net/jpg/02/50/14/90/360_F_250149090_D8gziruTx9UCuj4dsQCdXWHOBBHVR9iV.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Outdoor'],
    'description': 'A popular vegetable with red, round fruits.',
    'minTemp': 18.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Carrot',
    'imageUrl':
        'https://static.vecteezy.com/system/resources/thumbnails/046/366/901/small/two-carrots-are-planted-in-the-dirt-one-of-which-is-sprouting-photo.jpg',
    'soilType': 'Sandy',
    'weatherType': ['Cool', 'Sunny'],
    'categoryType': ['Outdoor'],
    'description': 'A root vegetable known for its orange color.',
    'minTemp': 10.0,
    'maxTemp': 24.0,
  },
  {
    'name': 'Basil',
    'imageUrl':
        'https://cdn.pixabay.com/photo/2015/09/09/17/38/basil-932079_640.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Indoor', 'Outdoor'],
    'description': 'An aromatic herb used in cooking.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Cucumber',
    'imageUrl':
        'https://www.shutterstock.com/image-photo/organic-cucumbers-cultivation-closeup-fresh-600nw-2463149627.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Warm', 'Moderate'],
    'categoryType': ['Outdoor'],
    'description': 'A vegetable with a crunchy texture, often used in salads.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Chili Pepper',
    'imageUrl':
        'https://www.bhg.com/thmb/HsMOFWa_w277lGQr_9LDrzbKEhU=/1244x0/filters:no_upscale():strip_icc()/red-serrano-peppers-AxBZ4UJpqDA8I3d81q9FEv-a530c96f2e1a41b198c89c2988759548.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Outdoor'],
    'description': 'A hot and spicy vegetable used in cooking.',
    'minTemp': 18.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Lettuce',
    'imageUrl':
        'https://static.vecteezy.com/system/resources/thumbnails/026/511/080/small_2x/lettuce-growing-in-the-garden-ai-generated-photo.jpg',
    'soilType': 'Silty',
    'weatherType': ['Cool', 'Moderate'],
    'categoryType': ['Outdoor'],
    'description': 'A leafy green vegetable often used in salads.',
    'minTemp': 10.0,
    'maxTemp': 20.0,
  },
  {
    'name': 'Strawberry',
    'imageUrl':
        'https://static9.depositphotos.com/1027431/1163/i/450/depositphotos_11637521-stock-photo-strawberry-plant.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Moderate', 'Sunny'],
    'categoryType': ['Outdoor', 'Garden'],
    'description': 'A sweet, red berry fruit.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Peas',
    'imageUrl':
        'https://www.thespruce.com/thmb/TFkDtO5bwzcv933ZM4R29SKbZ_g=/5750x0/filters:no_upscale():max_bytes(150000):strip_icc()/garden-vs-snow-and-sugar-snap-1403487-04-4216b24a579a4a899e7db3a44e4fe0e3.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Cool', 'Moderate'],
    'categoryType': ['Outdoor', 'Garden'],
    'description': 'A cool-season vegetable with edible pods.',
    'minTemp': 12.0,
    'maxTemp': 25.0,
  },
  {
    'name': 'Garlic',
    'imageUrl':
        'https://t3.ftcdn.net/jpg/06/06/38/70/360_F_606387045_qLNUQ72Bz4ck0KfcLcPN9kOgI55xXFCF.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Cool', 'Dry'],
    'categoryType': ['Outdoor', 'Garden'],
    'description': 'A pungent bulb used in cooking.',
    'minTemp': 10.0,
    'maxTemp': 20.0,
  },
  {
    'name': 'Chives',
    'imageUrl':
        'https://thumbs.dreamstime.com/b/chives-allium-schoenoprasum-plant-saint-gallen-switzerland-may-botanical-garden-324518968.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Cool', 'Moderate'],
    'categoryType': ['Indoor', 'Outdoor'],
    'description': 'A mild herb used for garnishing dishes.',
    'minTemp': 12.0,
    'maxTemp': 25.0,
  },
  {
    'name': 'Zucchini',
    'imageUrl':
        'https://www.theartofdoingstuff.com/wp-content/uploads/2019/07/Staking-zucchini-5.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Outdoor'],
    'description': 'A green vegetable, also called summer squash.',
    'minTemp': 18.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Avocado',
    'imageUrl':
        'https://www.treehugger.com/thmb/zQUGUvmtwss_oAa1lJvjUSQl4JA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/13-c510f41c08d74f1480c582cd5496320a.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Warm', 'Tropical'],
    'categoryType': ['Outdoor'],
    'description': 'A tropical fruit that is creamy and rich.',
    'minTemp': 20.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Lemon',
    'imageUrl':
        'https://cdn.britannica.com/84/188484-050-F27B0049/lemons-tree.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Outdoor'],
    'description': 'A citrus fruit with a tart flavor.',
    'minTemp': 20.0,
    'maxTemp': 35.0,
  },
  {
    'name': 'Sweet Potato',
    'imageUrl':
        'https://stonepostgardens.com/wp-content/uploads/2024/07/how-to-grow-purple-sweet-potatoes.png',
    'soilType': 'Sandy',
    'weatherType': ['Warm', 'Dry'],
    'categoryType': ['Outdoor'],
    'description': 'A starchy, sweet root vegetable.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Cabbage',
    'imageUrl':
        'https://kellogggarden.com/wp-content/uploads/2021/03/Cabbage.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Cool', 'Moderate'],
    'categoryType': ['Outdoor'],
    'description': 'A leafy green vegetable commonly used in salads and stews.',
    'minTemp': 12.0,
    'maxTemp': 25.0,
  },
  {
    'name': 'Oregano',
    'imageUrl':
        'https://thumbs.dreamstime.com/b/oregano-plant-texture-small-farm-as-nice-background-327907868.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Indoor', 'Outdoor'],
    'description': 'A fragrant herb used in Italian cuisine.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Eggplant',
    'imageUrl': 'https://i.ytimg.com/vi/Ppi1fNKhhTk/sddefault.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Outdoor'],
    'description': 'A purple vegetable with a mild, meaty texture.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Spinach',
    'imageUrl':
        'https://t4.ftcdn.net/jpg/10/50/08/93/360_F_1050089394_lYpqjKXK7LyZKGCIHX3aPYccvllrElVY.jpg',
    'soilType': 'Loamy',
    'weatherType': ['Cool', 'Moderate'],
    'categoryType': ['Outdoor'],
    'description': 'A leafy green vegetable often used in salads.',
    'minTemp': 10.0,
    'maxTemp': 20.0,
  },
  {
    'name': 'Rosemary',
    'imageUrl':
        'https://t4.ftcdn.net/jpg/01/08/56/75/360_F_108567569_WiQKRWvRKB3XltSvUc45OTO0oN4Gdvxz.jpg',
    'soilType': 'Well-drained, Sandy',
    'weatherType': ['Sunny', 'Warm'],
    'categoryType': ['Outdoor'],
    'description':
        'A fragrant herb commonly used in cooking and for medicinal purposes.',
    'minTemp': 15.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Lemon Balm',
    'imageUrl':
        'https://thumbs.dreamstime.com/b/lemon-balm-plant-garden-18811288.jpg',
    'soilType': 'Well-drained',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Indoor'],
    'description':
        'A fragrant herb with a strong lemon scent, often used for teas and relaxation.',
    'minTemp': 10.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Coriander',
    'imageUrl':
        'https://celebratedherb.com/wp-content/uploads/2024/06/IMG_3381.jpg',
    'soilType': 'Well-drained, Loamy',
    'weatherType': ['Warm', 'Sunny'],
    'categoryType': ['Outdoor'],
    'description':
        'A herb with fragrant leaves used in many culinary dishes, also known as cilantro.',
    'minTemp': 18.0,
    'maxTemp': 30.0,
  },
  {
    'name': 'Radish',
    'imageUrl':
        'https://cleangreensimple.com/wp-content/uploads/radishes-growing-in-container-800x600.jpg',
    'soilType': 'Well-drained, Loamy',
    'weatherType': ['Cool', 'Sunny'],
    'categoryType': ['Garden'],
    'description': 'A fast-growing vegetable known for its crisp, spicy roots.',
    'minTemp': 5.0,
    'maxTemp': 20.0,
  },
  {
    'name': 'Potato',
    'imageUrl':
        'https://t3.ftcdn.net/jpg/04/52/75/46/360_F_452754668_F8QX82iY9YCEeywoXa7KSLufO03eY4G3.jpg',
    'soilType': 'Loamy, Well-drained',
    'weatherType': ['Cool', 'Sunny'],
    'categoryType': ['Garden'],
    'description':
        'A starchy tuber commonly grown for food, providing high nutritional value.',
    'minTemp': 10.0,
    'maxTemp': 20.0,
  },
];
